User Profile Pages, Global Responsive Nav, Responsive User Profile Nav
Razorback360/SWE363-Project pull request #4
Opened 2024-11-08 19:36 UTC by Razorback360

2024-11-08 20:04 UTC, Razorback360 commented
![image](https://github.com/user-attachments/assets/219e0aa6-f5b1-4e61-9052-604f5c653ecb)
![image](https://github.com/user-attachments/assets/43fd9049-8742-4c7f-854d-95c014b56006)
![image](https://github.com/user-attachments/assets/36337b38-f57b-488d-a98b-b9cdf1e1ad38)
![image](https://github.com/user-attachments/assets/845cc8c8-58dc-4de7-9987-5f46c11f7e94)
![image](https://github.com/user-attachments/assets/a2eb47ff-56f5-4c53-852d-cca27b226b83)
![image](https://github.com/user-attachments/assets/6177da9a-2105-4a9d-9ede-c65be4dc5d80)

2024-11-08 20:31 UTC, Yokozuna59 requested changes
Please delete `npm` related files (e.g. `package-lock.json`) and use `pnpm` instead.
Also, please format files and remove unused imports.

2024-11-08 20:31 UTC, Yokozuna59 commented on client/src/pages/profile/donations.tsx
React JSX file names should start with caps letters. Rename the file to `Donations.tsx`. Same goes to `Donation.css`.

2024-11-08 20:31 UTC, Yokozuna59 commented on client/src/pages/profile/mobile.tsx
React JSX file names should start with caps letters. Rename the file to `Mobile.tsx`.

2024-11-09 10:00 UTC, Razorback360 commented on client/src/pages/profile/donations.tsx
resolved

2024-11-09 10:23 UTC, Yokozuna59 commented on client/src/pages/profile/mobile.tsx
If you say so. The syntax highlighting for those file isn't working so I assumed it wasn't on purpose.

2024-11-09 10:27 UTC, Yokozuna59 reviewed
There's still some `npm` related stuff:

- https://github.com/Razorback360/SWE363-Project/blob/5c572a12d6652f104939a19d56582306260b88b6/client/package.json#L15
- https://github.com/Razorback360/SWE363-Project/blob/5c572a12d6652f104939a19d56582306260b88b6/server/package.json#L17

2024-11-09 10:42 UTC, Yokozuna59 approved these changes

2024-11-09 10:42 UTC, merged